// SPDX-License-Identifier: Apache-2.0

package importer

import (
	"github.com/braunma/netbox-gitops-controller/pkg/client"
	"github.com/braunma/netbox-gitops-controller/pkg/models"
	"github.com/braunma/netbox-gitops-controller/pkg/utils"
)

// genHeader is the header stamped on every generated file. It carries no
// timestamp, run id or instance URL, so a re-import of an unchanged instance
// produces identical bytes.
func genHeader(what string) string {
	return "Generated by `netbox-gitops import` from a live NetBox instance.\n" +
		"\n" +
		what + "\n" +
		"\n" +
		"This is an ordinary file now: it is applied like any other, and a\n" +
		"re-import overwrites it. Review it before committing."
}

// siteAllowed reports whether a site slug passes the --site source filter.
func (rc *runContext) siteAllowed(slug string) bool {
	if len(rc.opts.Sites) == 0 {
		return true
	}
	for _, s := range rc.opts.Sites {
		if s == slug {
			return true
		}
	}
	return false
}

// foundation imports sites, racks, roles, tags, platforms, tenant groups,
// tenants and custom fields.
func (rc *runContext) foundation() error {
	steps := []func() error{
		rc.importSites,
		rc.importRacks,
		rc.importRoles,
		rc.importTags,
		rc.importPlatforms,
		rc.importTenantGroups,
		rc.importTenants,
		rc.importCustomFields,
	}
	for _, step := range steps {
		if err := step(); err != nil {
			return err
		}
	}
	return nil
}

func (rc *runContext) importSites() error {
	objs, err := rc.f.list("dcim", "sites", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		slug := str(o, "slug")
		if !rc.siteAllowed(slug) {
			continue
		}
		site := &models.Site{
			Name:        str(o, "name"),
			Slug:        slug,
			Status:      choiceValue(o, "status"),
			Region:      refSlug(o, "region"),
			TimeZone:    str(o, "time_zone"),
			Description: str(o, "description"),
			Comments:    str(o, "comments"),
			Tags:        tagSlugs(o, rc.strip),
		}
		if site.Region != "" {
			rc.report.note("site.region: regions are referenced but not imported as their own definitions")
		}
		items = append(items, site)
		exported++
	}
	rc.report.count("dcim/sites", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/sites/sites.yaml",
		genHeader("Every site this NetBox holds."), "items", items)
}

func (rc *runContext) importRacks() error {
	objs, err := rc.f.list("dcim", "racks", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		siteSlug := refSlug(o, "site")
		if !rc.siteAllowed(siteSlug) {
			continue
		}
		rack := &models.Rack{
			Name: str(o, "name"),
			// NetBox racks have no slug of their own; the YAML slug is this
			// project's concept, derived from the name and reused verbatim by
			// every device's rack_slug.
			Slug:        utils.Slugify(str(o, "name")),
			SiteSlug:    siteSlug,
			Status:      choiceValue(o, "status"),
			Width:       intOf(o, "width"),
			UHeight:     intOf(o, "u_height"),
			Description: str(o, "description"),
			Tags:        tagSlugs(o, rc.strip),
		}
		if w := nested(o, "width"); w != nil {
			// width serialises as a choice on some releases.
			rack.Width = intOf(client.Object(w), "value")
		}
		items = append(items, rack)
		exported++
	}
	rc.report.count("dcim/racks", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/racks/racks.yaml",
		genHeader("Every rack this NetBox holds. The slug is derived from the name;\n"+
			"devices reference it by that slug."), "items", items)
}

func (rc *runContext) importRoles() error {
	objs, err := rc.f.list("dcim", "device-roles", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		items = append(items, &models.Role{
			Name:        str(o, "name"),
			Slug:        str(o, "slug"),
			Color:       utils.NormalizeColor(str(o, "color")),
			VMRole:      boolOf(o, "vm_role"),
			Description: str(o, "description"),
		})
		exported++
	}
	rc.report.count("dcim/device-roles", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/roles/roles.yaml",
		genHeader("Every device role this NetBox holds."), "items", items)
}

func (rc *runContext) importTags() error {
	objs, err := rc.f.list("extras", "tags", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		slug := str(o, "slug")
		// The managed tag (and any sandbox tag) is machinery, not data: the
		// sync recreates the managed tag itself, so importing it would be noise.
		if rc.strip[slug] {
			continue
		}
		if !rc.keep(o) {
			continue
		}
		items = append(items, &models.Tag{
			Name:        str(o, "name"),
			Slug:        slug,
			Color:       utils.NormalizeColor(str(o, "color")),
			Description: str(o, "description"),
		})
		exported++
	}
	rc.report.count("extras/tags", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/extras/tags.yaml",
		genHeader("Every tag this NetBox holds, except the gitops-managed tag the\n"+
			"sync maintains itself."), "items", items)
}

func (rc *runContext) importPlatforms() error {
	objs, err := rc.f.list("dcim", "platforms", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		items = append(items, &models.Platform{
			Name: str(o, "name"),
			Slug: str(o, "slug"),
			// The model keys manufacturer by name; the sync ensures it by name.
			Manufacturer: refName(o, "manufacturer"),
			Description:  str(o, "description"),
			Tags:         tagSlugs(o, rc.strip),
		})
		exported++
	}
	rc.report.count("dcim/platforms", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/platforms/platforms.yaml",
		genHeader("Every platform this NetBox holds."), "items", items)
}

func (rc *runContext) importTenantGroups() error {
	objs, err := rc.f.list("tenancy", "tenant-groups", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		items = append(items, &models.TenantGroup{
			Name:        str(o, "name"),
			Slug:        str(o, "slug"),
			ParentSlug:  refSlug(o, "parent"),
			Description: str(o, "description"),
			Tags:        tagSlugs(o, rc.strip),
		})
		exported++
	}
	rc.report.count("tenancy/tenant-groups", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/tenant_groups/tenant_groups.yaml",
		genHeader("Every tenant group this NetBox holds."), "items", items)
}

func (rc *runContext) importTenants() error {
	objs, err := rc.f.list("tenancy", "tenants", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		items = append(items, &models.Tenant{
			Name:        str(o, "name"),
			Slug:        str(o, "slug"),
			GroupSlug:   refSlug(o, "group"),
			Description: str(o, "description"),
			Tags:        tagSlugs(o, rc.strip),
		})
		exported++
	}
	rc.report.count("tenancy/tenants", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/tenants/tenants.yaml",
		genHeader("Every tenant this NetBox holds."), "items", items)
}

func (rc *runContext) importCustomFields() error {
	objs, err := rc.f.list("extras", "custom-fields", nil)
	if err != nil {
		return err
	}
	var items []interface{}
	exported := 0
	for _, o := range objs {
		if !rc.keep(o) {
			continue
		}
		cf := &models.CustomField{
			Name:        str(o, "name"),
			Type:        choiceValue(o, "type"),
			ObjectTypes: stringList(o, "object_types"),
			Label:       str(o, "label"),
			Description: str(o, "description"),
			Required:    boolOf(o, "required"),
		}
		items = append(items, cf)
		exported++
	}
	rc.report.count("extras/custom-fields", len(objs), exported)
	if len(items) == 0 {
		return nil
	}
	return rc.emit("definitions/custom_fields/custom_fields.yaml",
		genHeader("Every custom field definition this NetBox holds. A device or VM\n"+
			"only sets a value into a field defined here."), "items", items)
}

// stringList coerces a NetBox list-of-strings field (e.g. custom-field
// object_types) to []string.
func stringList(obj client.Object, key string) []string {
	raw, ok := obj[key].([]interface{})
	if !ok {
		return nil
	}
	var out []string
	for _, v := range raw {
		if s, ok := v.(string); ok {
			out = append(out, s)
		}
	}
	return out
}
