# -----------------------------------------------------------------------------
# VM inventory (generated)
# -----------------------------------------------------------------------------
# This is populated by `cmd/tfgen` (terraform/generated.tfvars.json) from the
# same YAML the NetBox controller consumes. Do not edit generated.tfvars.json by
# hand — change inventory/virtual/*.yaml and regenerate.
#
# Optional attributes use defaults so VMs that omit a field (tfgen drops empty
# values) still decode cleanly.
variable "vms" {
  description = "Map of VM name => VM definition, generated by cmd/tfgen."
  type = map(object({
    name     = string
    vmid     = number
    node     = string
    cluster  = optional(string, "")
    site     = optional(string, "")
    platform = optional(string, "")
    vcpus    = optional(number, 1)
    memory   = optional(number, 1024)
    disk     = optional(number, 0) # 0 = inherit the template's disk size
    tags     = optional(list(string), [])
    interfaces = optional(list(object({
      name     = optional(string, "eth0")
      vlan     = optional(string, "")
      ip       = optional(string, "")
      dns_name = optional(string, "")
      primary  = optional(bool, false)
    })), [])
  }))
}

# -----------------------------------------------------------------------------
# Proxmox connection (set via TF_VAR_* / masked CI variables)
# -----------------------------------------------------------------------------
variable "proxmox_endpoint" {
  description = "Proxmox VE API endpoint, e.g. https://pve.example.com:8006/"
  type        = string
}

variable "proxmox_api_token" {
  description = "Proxmox API token in 'user@realm!tokenid=secret' form."
  type        = string
  sensitive   = true
}

variable "proxmox_insecure" {
  description = "Skip TLS verification for the Proxmox endpoint."
  type        = bool
  default     = false
}

# -----------------------------------------------------------------------------
# Infrastructure mapping (environment-specific)
# -----------------------------------------------------------------------------
variable "datastore_id" {
  description = "Datastore for VM disks and the cloud-init drive."
  type        = string
  default     = "local-lvm"
}

variable "network_bridge" {
  description = "Bridge every VM NIC attaches to (assumed VLAN-aware)."
  type        = string
  default     = "vmbr0"
}

# NetBox models VLANs by name; Proxmox NICs need a numeric 802.1q tag. Map the
# VLAN names used in the YAML to their tags here. Names absent from the map are
# left untagged (native VLAN of the bridge).
variable "vlan_tags" {
  description = "VLAN name => 802.1q tag id."
  type        = map(number)
  default     = {}
}

variable "default_gateway" {
  description = "IPv4 gateway injected into cloud-init (empty = none)."
  type        = string
  default     = ""
}

variable "dns_servers" {
  description = "Cloud-init DNS servers (empty list = inherit template)."
  type        = list(string)
  default     = []
}

# Templates to clone from. tfgen emits the platform slug as the template *name*;
# the bpg provider clones by numeric template id, so we resolve name => id from
# Proxmox at plan time. Templates must carry this tag to be discovered.
variable "template_tags" {
  description = "Tag(s) identifying clonable templates in Proxmox."
  type        = list(string)
  default     = ["template"]
}

# -----------------------------------------------------------------------------
# Cloud-init credentials (optional)
# -----------------------------------------------------------------------------
variable "ci_username" {
  description = "Default cloud-init user (empty = leave template default)."
  type        = string
  default     = ""
}

variable "ci_ssh_keys" {
  description = "Public SSH keys injected via cloud-init."
  type        = list(string)
  default     = []
}
