// SPDX-License-Identifier: Apache-2.0

package ingest

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/braunma/netbox-gitops-controller/pkg/discovery"
)

// DiscoveredRoot is where files written from a scan live.
//
// It mirrors the hand-written layout one level down, so the reconciler's own
// folders pick these up without a special case: a generated VM is loaded like
// any VM, and a completed skeleton is loaded like any device the moment its
// underscore comes off.
const DiscoveredRoot = "inventory/discovered"

// DiscoveredVMDir and DiscoveredDeviceDir are the two subtrees of that root.
const (
	DiscoveredVMDir     = DiscoveredRoot + "/virtual"
	DiscoveredDeviceDir = DiscoveredRoot + "/hardware"
)

// unclusteredFile holds guests a source could not place in a NetBox cluster.
// It is parked, because a VM with neither a cluster nor a site is not a VM
// NetBox will accept, and only a human can say which site it belongs to.
const unclusteredFile = "_unclustered.yaml"

// generatedVMFile renders the complete, appliable YAML for the VMs a source
// found that this repository does not declare.
//
// Nothing volatile goes into the header — no scan timestamp, no run id — so a
// second scan of an unchanged cluster produces the identical bytes and an
// empty diff. The facts inside may of course change; that is the point.
func generatedVMFile(source, cluster string, vms []discovery.VM, parked bool) string {
	var b strings.Builder

	b.WriteString("# Generated by `netbox-gitops collect` from source \"" + source + "\".\n")
	b.WriteString("#\n")
	if cluster != "" {
		b.WriteString("# Every virtual machine below was found on that source and was declared\n")
		b.WriteString("# nowhere else in this repository when this file was written. It is an\n")
		b.WriteString("# ordinary inventory file: it is applied to NetBox like any other, and the\n")
		b.WriteString("# facts of the machines in it are refreshed here in place.\n")
		b.WriteString("#\n")
		b.WriteString("# To take a machine over, declare it in a file of your own. The next run\n")
		b.WriteString("# sees the two declarations, keeps yours, and removes the block from here.\n")
		b.WriteString("# A machine that stops answering is never removed by a scan — that is a\n")
		b.WriteString("# fact for you to interpret.\n")
	} else {
		b.WriteString("# NOT APPLIED — the underscore parks this file so the loader skips it.\n")
		b.WriteString("#\n")
		b.WriteString("# These guests could not be placed in a NetBox cluster: the source that\n")
		b.WriteString("# found them declares no `cluster:` in collectors.yaml. Give it one, or\n")
		b.WriteString("# add a site_slug to each VM below and rename this file without the\n")
		b.WriteString("# leading underscore.\n")
	}
	b.WriteString("#\n")
	b.WriteString("# Edits to keys a collector owns (" + strings.Join(VMWritableKeys, ", ") + ") are\n")
	b.WriteString("# overwritten by the next run. Everything else is yours.\n")
	b.WriteString("\n")

	sorted := append([]discovery.VM(nil), vms...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Name != sorted[j].Name {
			return sorted[i].Name < sorted[j].Name
		}
		return sorted[i].VMID < sorted[j].VMID
	})

	for _, vm := range sorted {
		b.WriteString(renderVM(vm, parked))
	}
	return b.String()
}

// renderVM writes one VM block. The key order is fixed here, not derived from
// a map, so the output is byte-stable.
func renderVM(vm discovery.VM, needsSite bool) string {
	var b strings.Builder

	b.WriteString("- name: " + quoted(vm.Name) + "\n")
	if vm.Cluster != "" {
		b.WriteString("  cluster: " + quoted(vm.Cluster) + "\n")
	} else if needsSite {
		b.WriteString("  site_slug: \"TODO\" # TODO: the site this VM belongs to (or give the source a cluster)\n")
	}
	if vm.Node != "" {
		b.WriteString("  node: " + quoted(vm.Node) + "\n")
	}
	if vm.Platform != "" {
		b.WriteString("  platform: " + quoted(vm.Platform) + "\n")
	}
	if vm.Status != "" {
		b.WriteString("  status: " + quoted(vm.Status) + "\n")
	}
	if vm.VCPUs > 0 {
		b.WriteString(fmt.Sprintf("  vcpus: %d\n", vm.VCPUs))
	}
	if vm.MemoryMB > 0 {
		b.WriteString(fmt.Sprintf("  memory: %d # MB\n", vm.MemoryMB))
	}
	if vm.DiskGB > 0 {
		b.WriteString(fmt.Sprintf("  disk: %d # GB\n", vm.DiskGB))
	}
	if vm.VMID > 0 {
		b.WriteString(fmt.Sprintf("  vmid: %d\n", vm.VMID))
	}

	if len(vm.Interfaces) > 0 {
		b.WriteString("  interfaces:\n")
		for _, nic := range vm.Interfaces {
			b.WriteString("    - name: " + quoted(nic.Name) + "\n")
			if nic.MAC != "" {
				b.WriteString("      mac_address: " + quoted(nic.MAC) + "\n")
			}
			if !nic.Enabled {
				b.WriteString("      enabled: false\n")
			}
			// The interface model carries one `ip:` mapping, so a NIC with
			// several addresses gets its first one written and the rest listed
			// as a comment rather than silently dropped.
			if len(nic.IPs) > 0 {
				b.WriteString("      ip:\n")
				b.WriteString("        address: " + quoted(nic.IPs[0]) + "\n")
			}
			if len(nic.IPs) > 1 {
				b.WriteString("      # also seen on this NIC: " + strings.Join(nic.IPs[1:], ", ") + "\n")
			}
		}
	}

	b.WriteString("\n")
	return b.String()
}

// parkedDeviceFile renders the skeleton for a scanned machine this repository
// has never heard of.
//
// It is parked on purpose. A scan reaches a BMC over the network; it cannot
// know which site the machine stands in, which rack, which unit, which way it
// faces, what role it plays or which device type it is. Guessing any of those
// would put a plausible fiction into NetBox, so they are left as TODOs for a
// person who can actually walk into the room.
func parkedDeviceFile(source string, dev discovery.Device, prefix string) string {
	var b strings.Builder

	b.WriteString("# Generated by `netbox-gitops ingest` from source \"" + source + "\" — NOT APPLIED.\n")
	b.WriteString("#\n")
	b.WriteString("# The leading underscore parks this file: the loader skips it and says so,\n")
	b.WriteString("# so it can sit here until somebody finishes it.\n")
	b.WriteString("#\n")
	b.WriteString("# A scan found this machine but this repository does not declare it. What a\n")
	b.WriteString("# scan cannot know is marked TODO below — where the machine stands and what\n")
	b.WriteString("# it is for. Fill those in, drop the leading underscore from the filename\n")
	b.WriteString("# (or move the block into the file for its rack), and run\n")
	b.WriteString("#\n")
	b.WriteString("#   go run ./cmd/yamlcheck definitions inventory\n")
	b.WriteString("#\n")
	b.WriteString("# before opening the merge request. The `" + prefix + "` custom fields and the\n")
	b.WriteString("# serial and asset tag are refreshed by every scan; everything else is yours.\n")
	b.WriteString("\n")

	b.WriteString("- name: " + quoted(deviceSkeletonName(dev)) + " # TODO: the name this device should carry in NetBox\n")
	b.WriteString("  site_slug: \"TODO\" # TODO\n")
	b.WriteString("  role_slug: \"TODO\" # TODO\n")
	b.WriteString("  device_type_slug: \"TODO\" # TODO")
	if dev.Model != "" {
		b.WriteString(" — the scan reports the model as " + dev.Model)
	}
	b.WriteString("\n")
	b.WriteString("  rack_slug: \"TODO\" # TODO\n")
	b.WriteString("  position: 0 # TODO: lowest rack unit the chassis occupies\n")
	b.WriteString("  face: \"front\" # TODO: front or rear\n")
	if dev.Serial != "" {
		b.WriteString("  serial: " + quoted(dev.Serial) + "\n")
	}
	if dev.ServiceTag != "" {
		b.WriteString("  asset_tag: " + quoted(dev.ServiceTag) + "\n")
	}

	if fields := hardwareCustomFields(dev.HW, prefix); len(fields) > 0 {
		b.WriteString("  custom_fields:\n")
		for _, kv := range fields {
			text, err := formatScalar(kv.Value, yaml.DoubleQuotedStyle)
			if err != nil {
				// Unreachable for the scalar facts above, and a skipped field is
				// better than a broken file if it ever happens.
				continue
			}
			b.WriteString("    " + kv.Key + ": " + text + "\n")
		}
	}

	if dev.MgmtIP != "" || len(dev.Interfaces) > 0 {
		b.WriteString("\n")
		b.WriteString("  # What the scan saw on the wire. Add these under an `interfaces:` block\n")
		b.WriteString("  # once the device type is known, so the port names match its template.\n")
		if dev.MgmtIP != "" {
			b.WriteString("  #   management address: " + dev.MgmtIP + "\n")
		}
		for _, nic := range dev.Interfaces {
			line := "  #   " + nic.Name
			if nic.MAC != "" {
				line += "  " + nic.MAC
			}
			if len(nic.IPs) > 0 {
				line += "  " + strings.Join(nic.IPs, " ")
			}
			b.WriteString(line + "\n")
		}
	}

	return b.String()
}

// deviceSkeletonName is the best name the scan knows, or a placeholder. It is a
// starting point for a human, never an authority.
func deviceSkeletonName(dev discovery.Device) string {
	if name := strings.TrimSpace(dev.Name); name != "" {
		return name
	}
	if id := deviceIdentifier(dev); id != "" {
		return "TODO-" + id
	}
	return "TODO-rename-me"
}

// deviceIdentifier is the most stable thing the scan reported, used to name the
// skeleton's file so a second scan of the same machine lands on the same path.
func deviceIdentifier(dev discovery.Device) string {
	for _, candidate := range []string{dev.Serial, dev.ServiceTag, dev.Name, dev.MgmtIP} {
		if trimmed := strings.TrimSpace(candidate); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

// parkedDevicePath is where a scanned but undeclared machine's skeleton goes.
func parkedDevicePath(source string, dev discovery.Device) string {
	id := fileSlug(deviceIdentifier(dev))
	if id == "" {
		id = "unidentified"
	}
	return path.Join(DiscoveredDeviceDir, fileSlug(source), "_"+id+".yaml")
}

// generatedVMPath is where a source's undeclared guests go, one file per
// cluster so a big estate stays reviewable.
func generatedVMPath(source, cluster string) string {
	if cluster == "" {
		return path.Join(DiscoveredVMDir, fileSlug(source), unclusteredFile)
	}
	return path.Join(DiscoveredVMDir, fileSlug(source), fileSlug(cluster)+".yaml")
}

// unsafeFileChars is everything that has no business in a generated filename.
var unsafeFileChars = regexp.MustCompile(`[^a-z0-9._-]+`)

// fileSlug makes a value safe to use as a path segment.
func fileSlug(value string) string {
	slug := unsafeFileChars.ReplaceAllString(strings.ToLower(strings.TrimSpace(value)), "-")
	slug = strings.Trim(slug, "-._")
	return slug
}

// quoted renders a string as a double-quoted YAML scalar, which is what the
// hand-written inventory files use throughout.
func quoted(value string) string {
	text, err := formatScalar(value, 0)
	if err != nil {
		return `""`
	}
	if strings.HasPrefix(text, `"`) || strings.HasPrefix(text, `'`) {
		return text
	}
	return `"` + strings.ReplaceAll(strings.ReplaceAll(value, `\`, `\\`), `"`, `\"`) + `"`
}
